global:
    scrape_interval: 2s
    evaluation_interval: 2s

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'demo'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
